### PR TITLE
[37]  Add prettier-plugin-tailwindcss

### LINKED ISSUE #37: Add prettier-plugin-tailwindcss
For sorting classes in tailwind

https://github.com/tailwindlabs/prettier-plugin-tailwindcss

### PR DESCRIPTION
**Pull request by n0macx**
Closes #37 

Information:

- [x] Do your changes affect most of the application?
  - [x] Did you describe it in the task?
  - [x] Did you inform others about it on Slack?
- [x] Have you installed a new library?
  - [x] Have you consulted it with the others?

Checklist:

- [x] Does the Pull Request title meet the rules? (eg. `[9] Add name's rules for PR to readme`)
- [x] Does the name of your branch meet the rules? (eg. `9-add-names-rules-for-pr-to-readme`)
- [x] Does the Pull Request description contain `Closes #<issue number>` (eg. `Closes #9`)?
- [x] Did Husky run all jobs? (you didn't use the `no-verify` flag)
- [x] Did you describe the task in the linked issue? (AC, useful links, description)
- [x] Did you link the issue to the pull request through the `Development` tab in the pull request options?

Remainders:

- Make sure your commit messages contain useful information
- Make sure to use pnpm and do not push other lock files

### CODE REVIEW

**Review by jedrzejratajczak — COMMENTED** [review]
How about switching to `.prettierrc` file? It will be a bit cleaner

**Comment by n0macx** [comment]
> 

Done. Thanks for the comment.

**Comment by jedrzejratajczak** [comment]
I mean `.prettierrc`, it's a JSON type of file, not JS. The content should be:
```JSON
{
  "plugins": ["prettier-plugin-tailwindcss"]
}
```
Like in the docs: https://prettier.io/docs/en/plugins.html

**Comment by n0macx** [comment]
> 

Ofcourse, no problem.

**Review by jedrzejratajczak — APPROVED** [review]

**Pull request merged**
